<?php
/**
 * @file
 * course_info.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function course_info_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: navigation:node/add/course
  $menu_links['navigation:node/add/course'] = array(
    'menu_name' => 'navigation',
    'link_path' => 'node/add/course',
    'router_path' => 'node/add/course',
    'link_title' => 'Course',
    'options' => array(),
    'module' => 'system',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '0',
    'parent_path' => 'node/add',
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('Course');


  return $menu_links;
}
